# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_windownWuQyC.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

import os, sys

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QComboBox, QFrame,
    QGridLayout, QHBoxLayout, QHeaderView, QLabel,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QSpacerItem, QStatusBar, QTreeWidget,
    QTreeWidgetItem, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(728, 795)
        MainWindow.setMinimumSize(QSize(728, 795))
        MainWindow.setMaximumSize(QSize(1600, 1200))
        MainWindow.setSizeIncrement(QSize(0, 0))
        icon = QIcon()
        icon.addFile(self.resource_path('res/icons/project_72.png'), QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        icon1 = QIcon()
        icon1.addFile(self.resource_path('res/icons/icons8-opened-folder-64.png'), QSize(), QIcon.Normal, QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave.setEnabled(False)
        icon2 = QIcon()
        icon2.addFile(self.resource_path('res/icons/icons8-save-64.png'), QSize(), QIcon.Normal, QIcon.On)
        self.actionSave.setIcon(icon2)
        self.actionReindex = QAction(MainWindow)
        self.actionReindex.setObjectName(u"actionReindex")
        self.actionReindex.setEnabled(False)
        icon3 = QIcon()
        icon3.addFile(self.resource_path('res/icons/icons8-database-administrator-64.png'), QSize(), QIcon.Normal, QIcon.Off)
        self.actionReindex.setIcon(icon3)
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        icon4 = QIcon()
        icon4.addFile(self.resource_path('res/icons/icons8-export-64.png'), QSize(), QIcon.Normal, QIcon.Off)
        self.actionQuit.setIcon(icon4)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        icon5 = QIcon()
        icon5.addFile(self.resource_path('res/icons/icons8-info-64.png'), QSize(), QIcon.Normal, QIcon.Off)
        self.actionAbout.setIcon(icon5)
        self.actionHelp = QAction(MainWindow)
        self.actionHelp.setObjectName(u"actionHelp")
        self.actionHelp.setEnabled(True)
        icon6 = QIcon()
        icon6.addFile(self.resource_path('res/icons/icons8-help-64.png'), QSize(), QIcon.Normal, QIcon.Off)
        self.actionHelp.setIcon(icon6)
        self.actionSave_As = QAction(MainWindow)
        self.actionSave_As.setObjectName(u"actionSave_As")
        self.actionSave_As.setEnabled(False)
        icon7 = QIcon()
        icon7.addFile(self.resource_path('res/icons/icons8-save-as-64.png'), QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave_As.setIcon(icon7)
        self.actionExpand_All = QAction(MainWindow)
        self.actionExpand_All.setObjectName(u"actionExpand_All")
        self.actionExpand_All.setEnabled(False)
        icon8 = QIcon()
        icon8.addFile(self.resource_path('res/icons/icons8-expand-64.png'), QSize(), QIcon.Normal, QIcon.Off)
        self.actionExpand_All.setIcon(icon8)
        self.actionCollapse_All = QAction(MainWindow)
        self.actionCollapse_All.setObjectName(u"actionCollapse_All")
        self.actionCollapse_All.setEnabled(False)
        icon9 = QIcon()
        icon9.addFile(self.resource_path('res/icons/icons8-collapse-64.png'), QSize(), QIcon.Normal, QIcon.Off)
        self.actionCollapse_All.setIcon(icon9)
        self.actionSelect_All = QAction(MainWindow)
        self.actionSelect_All.setObjectName(u"actionSelect_All")
        self.actionSelect_All.setEnabled(False)
        icon10 = QIcon()
        icon10.addFile(self.resource_path('res/icons/icons8-double-tick-64.png'), QSize(), QIcon.Normal, QIcon.Off)
        self.actionSelect_All.setIcon(icon10)
        self.actionUnselect_All = QAction(MainWindow)
        self.actionUnselect_All.setObjectName(u"actionUnselect_All")
        self.actionUnselect_All.setEnabled(False)
        icon11 = QIcon()
        icon11.addFile(self.resource_path('res/icons/icons8-unchecked-checkbox-64.png'), QSize(), QIcon.Normal, QIcon.Off)
        self.actionUnselect_All.setIcon(icon11)
        self.actionCode_Title = QAction(MainWindow)
        self.actionCode_Title.setObjectName(u"actionCode_Title")
        self.actionCode_Title.setCheckable(True)
        self.actionCode_Title.setChecked(False)
        self.actionShort_Title = QAction(MainWindow)
        self.actionShort_Title.setObjectName(u"actionShort_Title")
        self.actionShort_Title.setCheckable(True)
        self.actionShort_Title.setChecked(True)
        self.actionFull_Title = QAction(MainWindow)
        self.actionFull_Title.setObjectName(u"actionFull_Title")
        self.actionFull_Title.setCheckable(True)
        self.actionGrouped = QAction(MainWindow)
        self.actionGrouped.setObjectName(u"actionGrouped")
        self.actionGrouped.setCheckable(True)
        self.actionGrouped.setChecked(False)
        self.actionGrouped.setEnabled(False)
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        icon12 = QIcon()
        icon12.addFile(self.resource_path('res/icons/icons8-add-file-64.png'), QSize(), QIcon.Normal, QIcon.Off)
        self.actionNew.setIcon(icon12)
        self.actionDetailed = QAction(MainWindow)
        self.actionDetailed.setObjectName(u"actionDetailed")
        self.actionDetailed.setCheckable(True)
        self.actionDetailed.setEnabled(False)
        self.actionObscure = QAction(MainWindow)
        self.actionObscure.setObjectName(u"actionObscure")
        self.actionObscure.setEnabled(False)
        icon13 = QIcon()
        icon13.addFile(self.resource_path('res/icons/icons8-invisible-64.png'), QSize(), QIcon.Normal, QIcon.Off)
        self.actionObscure.setIcon(icon13)
        self.actionImport = QAction(MainWindow)
        self.actionImport.setObjectName(u"actionImport")
        self.actionImport.setEnabled(False)
        icon14 = QIcon()
        icon14.addFile(self.resource_path('res/icons/icons8-import-csv-64.png'), QSize(), QIcon.Normal, QIcon.Off)
        self.actionImport.setIcon(icon14)
        self.actionEN = QAction(MainWindow)
        self.actionEN.setObjectName(u"actionEN")
        self.actionEN.setCheckable(True)
        self.actionEN.setChecked(True)
        self.actionES = QAction(MainWindow)
        self.actionES.setObjectName(u"actionES")
        self.actionES.setCheckable(True)
        self.actionDE = QAction(MainWindow)
        self.actionDE.setObjectName(u"actionDE")
        self.actionDE.setCheckable(True)
        self.actionFR = QAction(MainWindow)
        self.actionFR.setObjectName(u"actionFR")
        self.actionFR.setCheckable(True)
        self.actionPT = QAction(MainWindow)
        self.actionPT.setObjectName(u"actionPT")
        self.actionPT.setCheckable(True)
        self.actionIT = QAction(MainWindow)
        self.actionIT.setObjectName(u"actionIT")
        self.actionIT.setCheckable(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QSize(728, 747))
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.frame_info = QFrame(self.centralwidget)
        self.frame_info.setObjectName(u"frame_info")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.frame_info.sizePolicy().hasHeightForWidth())
        self.frame_info.setSizePolicy(sizePolicy1)
        self.frame_info.setMinimumSize(QSize(710, 80))
        self.frame_info.setMaximumSize(QSize(1600, 80))
        self.frame_info.setSizeIncrement(QSize(0, 0))
        self.frame_info.setFrameShape(QFrame.StyledPanel)
        self.frame_info.setFrameShadow(QFrame.Raised)
        self.horizontalLayout = QHBoxLayout(self.frame_info)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.info = QWidget(self.frame_info)
        self.info.setObjectName(u"info")
        self.info.setMinimumSize(QSize(460, 80))
        self.info.setMaximumSize(QSize(460, 80))
        self.combo_grouping = QComboBox(self.info)
        self.combo_grouping.addItem("")
        self.combo_grouping.addItem("")
        self.combo_grouping.addItem("")
        self.combo_grouping.addItem("")
        self.combo_grouping.addItem("")
        self.combo_grouping.setObjectName(u"combo_grouping")
        self.combo_grouping.setEnabled(False)
        self.combo_grouping.setGeometry(QRect(320, 30, 140, 28))
        self.total = QLabel(self.info)
        self.total.setObjectName(u"total")
        self.total.setGeometry(QRect(120, 0, 80, 28))
        self.total.setTextFormat(Qt.MarkdownText)
        self.total.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_grouping = QLabel(self.info)
        self.label_grouping.setObjectName(u"label_grouping")
        self.label_grouping.setGeometry(QRect(220, 30, 100, 28))
        self.selected = QLabel(self.info)
        self.selected.setObjectName(u"selected")
        self.selected.setGeometry(QRect(120, 30, 80, 28))
        self.selected.setTextFormat(Qt.MarkdownText)
        self.selected.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_selected = QLabel(self.info)
        self.label_selected.setObjectName(u"label_selected")
        self.label_selected.setGeometry(QRect(5, 30, 110, 28))
        self.label_category = QLabel(self.info)
        self.label_category.setObjectName(u"label_category")
        self.label_category.setGeometry(QRect(220, 0, 100, 28))
        self.combo_category = QComboBox(self.info)
        self.combo_category.addItem("")
        self.combo_category.addItem("")
        self.combo_category.addItem("")
        self.combo_category.addItem("")
        self.combo_category.addItem("")
        self.combo_category.setObjectName(u"combo_category")
        self.combo_category.setEnabled(False)
        self.combo_category.setGeometry(QRect(320, 0, 140, 28))
        self.label_total = QLabel(self.info)
        self.label_total.setObjectName(u"label_total")
        self.label_total.setGeometry(QRect(5, 0, 110, 28))

        self.horizontalLayout.addWidget(self.info)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.MinimumExpanding, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.buttons = QWidget(self.frame_info)
        self.buttons.setObjectName(u"buttons")
        self.buttons.setMinimumSize(QSize(175, 80))
        self.buttons.setMaximumSize(QSize(175, 80))
        self.button_import = QPushButton(self.buttons)
        self.button_import.setObjectName(u"button_import")
        self.button_import.setEnabled(False)
        self.button_import.setGeometry(QRect(90, 30, 85, 28))
        self.button_export = QPushButton(self.buttons)
        self.button_export.setObjectName(u"button_export")
        self.button_export.setEnabled(False)
        self.button_export.setGeometry(QRect(90, 0, 85, 28))
        self.button_delete = QPushButton(self.buttons)
        self.button_delete.setObjectName(u"button_delete")
        self.button_delete.setEnabled(False)
        self.button_delete.setGeometry(QRect(0, 30, 85, 28))
        self.button_add = QPushButton(self.buttons)
        self.button_add.setObjectName(u"button_add")
        self.button_add.setEnabled(True)
        self.button_add.setGeometry(QRect(0, 0, 85, 28))

        self.horizontalLayout.addWidget(self.buttons)


        self.verticalLayout.addWidget(self.frame_info)

        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.treeWidget = QTreeWidget(self.centralwidget)
        font = QFont()
        font.setBold(True)
        self.treeWidget.headerItem().setText(0, "")
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setTextAlignment(1, Qt.AlignCenter);
        __qtreewidgetitem.setFont(1, font);
        __qtreewidgetitem.setTextAlignment(0, Qt.AlignCenter);
        __qtreewidgetitem.setFont(0, font);
        self.treeWidget.setHeaderItem(__qtreewidgetitem)
        self.treeWidget.setObjectName(u"treeWidget")
        sizePolicy2 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy2)
        self.treeWidget.setMinimumSize(QSize(680, 641))
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.treeWidget.setAllColumnsShowFocus(True)
        self.treeWidget.setColumnCount(2)
        self.treeWidget.header().setMinimumSectionSize(150)
        self.treeWidget.header().setDefaultSectionSize(500)
        self.treeWidget.header().setHighlightSections(False)
        self.treeWidget.header().setProperty("showSortIndicator", True)
        self.treeWidget.header().setStretchLastSection(True)

        self.gridLayout.addWidget(self.treeWidget, 0, 0, 1, 1)


        self.verticalLayout.addLayout(self.gridLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 728, 25))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuTitle_View = QMenu(self.menuView)
        self.menuTitle_View.setObjectName(u"menuTitle_View")
        self.menuTitle_View.setEnabled(False)
        icon15 = QIcon()
        icon15.addFile(self.resource_path('res/icons/icons8-list-64.png'), QSize(), QIcon.Normal, QIcon.On)
        self.menuTitle_View.setIcon(icon15)
        self.menuLanguage = QMenu(self.menuView)
        self.menuLanguage.setObjectName(u"menuLanguage")
        self.menuUtilities = QMenu(self.menubar)
        self.menuUtilities.setObjectName(u"menuUtilities")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        self.statusBar.setSizeGripEnabled(False)
        MainWindow.setStatusBar(self.statusBar)
#if QT_CONFIG(shortcut)
        self.label_grouping.setBuddy(self.combo_grouping)
        self.label_category.setBuddy(self.combo_category)
#endif // QT_CONFIG(shortcut)
        QWidget.setTabOrder(self.combo_category, self.combo_grouping)
        QWidget.setTabOrder(self.combo_grouping, self.button_export)
        QWidget.setTabOrder(self.button_export, self.button_delete)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuUtilities.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuView.addAction(self.menuLanguage.menuAction())
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionExpand_All)
        self.menuView.addAction(self.actionCollapse_All)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionSelect_All)
        self.menuView.addAction(self.actionUnselect_All)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionDetailed)
        self.menuView.addAction(self.actionGrouped)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuTitle_View.menuAction())
        self.menuTitle_View.addAction(self.actionCode_Title)
        self.menuTitle_View.addAction(self.actionShort_Title)
        self.menuTitle_View.addAction(self.actionFull_Title)
        self.menuLanguage.addAction(self.actionEN)
        self.menuLanguage.addAction(self.actionDE)
        self.menuLanguage.addAction(self.actionES)
        self.menuLanguage.addAction(self.actionFR)
        self.menuLanguage.addAction(self.actionIT)
        self.menuLanguage.addAction(self.actionPT)
        self.menuUtilities.addAction(self.actionObscure)
        self.menuUtilities.addAction(self.actionReindex)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"JWLManager", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"&Open...", None))
#if QT_CONFIG(shortcut)
        self.actionOpen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"&Save", None))
#if QT_CONFIG(tooltip)
        self.actionSave.setToolTip(QCoreApplication.translate("MainWindow", u"Save archive", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionReindex.setText(QCoreApplication.translate("MainWindow", u"&Reindex", None))
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"&Quit", None))
#if QT_CONFIG(shortcut)
        self.actionQuit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"&About...", None))
        self.actionHelp.setText(QCoreApplication.translate("MainWindow", u"&Help", None))
        self.actionSave_As.setText(QCoreApplication.translate("MainWindow", u"Save &As...", None))
#if QT_CONFIG(tooltip)
        self.actionSave_As.setToolTip(QCoreApplication.translate("MainWindow", u"Save archive as...", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionSave_As.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionExpand_All.setText(QCoreApplication.translate("MainWindow", u"E&xpand All", None))
#if QT_CONFIG(tooltip)
        self.actionExpand_All.setToolTip(QCoreApplication.translate("MainWindow", u"Expand all items", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionExpand_All.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.actionCollapse_All.setText(QCoreApplication.translate("MainWindow", u"&Collapse All", None))
#if QT_CONFIG(tooltip)
        self.actionCollapse_All.setToolTip(QCoreApplication.translate("MainWindow", u"Collapse all items", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionCollapse_All.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionSelect_All.setText(QCoreApplication.translate("MainWindow", u"&Select All", None))
#if QT_CONFIG(tooltip)
        self.actionSelect_All.setToolTip(QCoreApplication.translate("MainWindow", u"Select all items", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionSelect_All.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.actionUnselect_All.setText(QCoreApplication.translate("MainWindow", u"&Unselect All", None))
#if QT_CONFIG(tooltip)
        self.actionUnselect_All.setToolTip(QCoreApplication.translate("MainWindow", u"Unselect all items", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionUnselect_All.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionCode_Title.setText(QCoreApplication.translate("MainWindow", u"Code", None))
#if QT_CONFIG(tooltip)
        self.actionCode_Title.setToolTip(QCoreApplication.translate("MainWindow", u"Use publication code as title", None))
#endif // QT_CONFIG(tooltip)
        self.actionShort_Title.setText(QCoreApplication.translate("MainWindow", u"Short Title", None))
#if QT_CONFIG(tooltip)
        self.actionShort_Title.setToolTip(QCoreApplication.translate("MainWindow", u"Use short publication title", None))
#endif // QT_CONFIG(tooltip)
        self.actionFull_Title.setText(QCoreApplication.translate("MainWindow", u"Full Title", None))
#if QT_CONFIG(tooltip)
        self.actionFull_Title.setToolTip(QCoreApplication.translate("MainWindow", u"Use full publication title", None))
#endif // QT_CONFIG(tooltip)
        self.actionGrouped.setText(QCoreApplication.translate("MainWindow", u"&Grouped", None))
#if QT_CONFIG(tooltip)
        self.actionGrouped.setToolTip(QCoreApplication.translate("MainWindow", u"Group publications by category", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionGrouped.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+G", None))
#endif // QT_CONFIG(shortcut)
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"&New", None))
#if QT_CONFIG(tooltip)
        self.actionNew.setToolTip(QCoreApplication.translate("MainWindow", u"Create an empty archive", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionNew.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionDetailed.setText(QCoreApplication.translate("MainWindow", u"&Detailed", None))
#if QT_CONFIG(shortcut)
        self.actionDetailed.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+D", None))
#endif // QT_CONFIG(shortcut)
        self.actionObscure.setText(QCoreApplication.translate("MainWindow", u"&Obscure", None))
        self.actionImport.setText(QCoreApplication.translate("MainWindow", u"&Import...", None))
#if QT_CONFIG(shortcut)
        self.actionImport.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+I", None))
#endif // QT_CONFIG(shortcut)
        self.actionEN.setText(QCoreApplication.translate("MainWindow", u"English", None))
        self.actionES.setText(QCoreApplication.translate("MainWindow", u"espa\u00f1ol", None))
        self.actionDE.setText(QCoreApplication.translate("MainWindow", u"Deutsch", None))
        self.actionFR.setText(QCoreApplication.translate("MainWindow", u"fran\u00e7ais", None))
        self.actionPT.setText(QCoreApplication.translate("MainWindow", u"portugu\u00eas", None))
        self.actionIT.setText(QCoreApplication.translate("MainWindow", u"italiano", None))
        self.combo_grouping.setItemText(0, QCoreApplication.translate("MainWindow", u"Publication", None))
        self.combo_grouping.setItemText(1, QCoreApplication.translate("MainWindow", u"Language", None))
        self.combo_grouping.setItemText(2, QCoreApplication.translate("MainWindow", u"Year", None))
        self.combo_grouping.setItemText(3, QCoreApplication.translate("MainWindow", u"Tag", None))
        self.combo_grouping.setItemText(4, QCoreApplication.translate("MainWindow", u"Color", None))

#if QT_CONFIG(tooltip)
        self.combo_grouping.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.total.setText("")
#if QT_CONFIG(tooltip)
        self.label_grouping.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_grouping.setText(QCoreApplication.translate("MainWindow", u"Grouping:", None))
        self.selected.setText("")
        self.label_selected.setText(QCoreApplication.translate("MainWindow", u"Selected:", None))
#if QT_CONFIG(tooltip)
        self.label_category.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_category.setText(QCoreApplication.translate("MainWindow", u"Category:", None))
        self.combo_category.setItemText(0, QCoreApplication.translate("MainWindow", u"Notes", None))
        self.combo_category.setItemText(1, QCoreApplication.translate("MainWindow", u"Highlights", None))
        self.combo_category.setItemText(2, QCoreApplication.translate("MainWindow", u"Favorites", None))
        self.combo_category.setItemText(3, QCoreApplication.translate("MainWindow", u"Bookmarks", None))
        self.combo_category.setItemText(4, QCoreApplication.translate("MainWindow", u"Annotations", None))

#if QT_CONFIG(tooltip)
        self.combo_category.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_total.setText(QCoreApplication.translate("MainWindow", u"Total:", None))
        self.button_import.setText(QCoreApplication.translate("MainWindow", u"Import", None))
        self.button_export.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.button_delete.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.button_add.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        ___qtreewidgetitem = self.treeWidget.headerItem()
        ___qtreewidgetitem.setText(1, QCoreApplication.translate("MainWindow", u"Count", None));
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"&File", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"&Help", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"&View", None))
#if QT_CONFIG(tooltip)
        self.menuTitle_View.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.menuTitle_View.setTitle(QCoreApplication.translate("MainWindow", u"Title View", None))
        self.menuLanguage.setTitle(QCoreApplication.translate("MainWindow", u"&Language", None))
        self.menuUtilities.setTitle(QCoreApplication.translate("MainWindow", u"&Utilities", None))
    # retranslateUi

    def resource_path(self, relative_path):
        try:
            base_path = sys._MEIPASS
        except Exception:
            base_path = os.path.abspath(".")
        return os.path.join(base_path, relative_path)
