name: 'Build macOS15+ with Nuitka v1.1.0'

on:
  workflow_call:
    inputs:
      TAG:
        default: 'testing'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      TAG:
        default: 'testing'
        required: true
        type: string

jobs:
  macos:
    name: Build macOS APP
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r res/requirements.txt
    - name: Build with Nuitka
      run: |
        python -m pip install nuitka==2.6.5
        python -m nuitka --mode=onefile --windows-icon-from-ico='res/icons/JWLManager.ico' --include-data-dir=res=res --include-module=xlsx2csv --include-package-data=puremagic --enable-plugin=pyside6 --clang --assume-yes-for-downloads JWLManager.py
        pwd
        ls
        mkdir dist
        mv JWLManager.bin dist/JWLManager_${{ inputs.TAG }}
    - name: Zip app
      run: |
        cd dist/
        zip -r9 JWLManager_${{ inputs.TAG }}.app.zip JWLManager.app/
    - name: Upload APP
      uses: actions/upload-artifact@v4
      with:
        name: MacAPP
        path: dist/JWLManager_${{ inputs.TAG }}.app.zip
