name: 'Build Linux package v1.0.2'

on:
  workflow_call:
    inputs:
      TAG:
        default: 'testing'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      TAG:
        default: 'testing'
        required: true
        type: string

jobs:
  linux:
    name: Build Linux BIN
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r res/requirements.txt
        pip install pyinstaller
        pip install pyinstaller-hooks-contrib
    - name: Build with Pyinstaller
      run: |
        pyinstaller --clean --noconfirm .github/workflows/JWLManager.bin.spec
        mv dist/JWLManager dist/JWLManager_${{ inputs.TAG }}
    - name: Upload BIN
      uses: actions/upload-artifact@v4
      with:
        name: LinuxBIN
        path: dist/JWLManager_${{ inputs.TAG }}
