name: 'Build Linux with Nuitka v1.1.0'

on:
  workflow_call:
    inputs:
      TAG:
        default: 'testing'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      TAG:
        default: 'testing'
        required: true
        type: string

jobs:
  linux:
    name: Build Linux BIN
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r res/requirements.txt
        python -m pip install nuitka==2.6.5
    - name: Build with Nuitka
      run: |
        python -m nuitka --mode=onefile --windows-icon-from-ico='res/icons/JWLManager.ico' --include-data-dir=res=res --include-module=xlsx2csv --include-package-data=puremagic --enable-plugin=pyside6 --clang --assume-yes-for-downloads JWLManager.py
        mkdir dist
        cp JWLManager.bin dist/JWLManager_${{ inputs.TAG }}
    - name: Upload BIN
      uses: actions/upload-artifact@v4
      with:
        name: LinuxBIN
        path: dist/JWLManager_${{ inputs.TAG }}
