name: 'Build Windows packages v1.0.1'

on:
  workflow_call:
    inputs:
      TAG:
        default: 'testing'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      TAG:
        default: 'testing'
        required: true
        type: string

jobs:
  windows:
    name: Build Windows EXE & ZIP
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r res/requirements.txt
        pip install nuitka
    - name: Build EXE with Nuitka
      run: |
        echo "PATH=$PATH:C:\msys64\mingw64\bin" >> $GITHUB_ENV
        python -m nuitka --onefile --windows-console-mode=disable --windows-icon-from-ico='res/icons/JWLManager.ico' --include-data-dir=res=res --include-module=xlsx2csv --enable-plugin=pyside6 --msvc=latest JWLManager.py
    - name: Rename EXE
      run: |
        cd dist
        ren JWLManager.exe JWLManager_${{ inputs.TAG }}.exe
    # - name: Build with Pyinstaller
    #   run: |
    #     pyinstaller --clean --noconfirm .github/workflows/JWLManager.zip.spec
    # - name: Rename & zip folder
    #   run: |
    #     cd dist
    #     tar.exe -a -c -f JWLManager_${{ inputs.TAG }}.zip JWLManager
    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: WindowsEXE
        path: dist/JWLManager_${{ inputs.TAG }}.exe
    # - name: Upload ZIP
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: WindowsZIP
    #     path: dist/JWLManager_${{ inputs.TAG }}.zip