name: 'Draft Release v1.0.0'

on:
  push:
    tags:
      - 'v*'

jobs:
  linux:
    uses: ./.github/workflows/build_lin.yml
    with:
      TAG:  ${{ github.ref_name }}
  windows:
    uses: ./.github/workflows/build_win.yml
    with:
      TAG:  ${{ github.ref_name }}
  macOS:
    uses: ./.github/workflows/build_mac.yml
    with:
      TAG:  ${{ github.ref_name }}
  release:
    name: Create Release Draft
    needs: [linux, windows, macos]
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.ref_name }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download LinuxBIN
      uses: actions/download-artifact@v4
      with:
        name: LinuxBIN
    - name: Download WindowsEXE
      uses: actions/download-artifact@v4
      with:
        name: WindowsEXE
    - name: Download WindowsZIP
      uses: actions/download-artifact@v4
      with:
        name: WindowsZIP
    - name: Download MacAPP
      uses: actions/download-artifact@v4
      with:
        name: MacAPP
    - name: Extract release notes
      id: extract-release-notes
      uses: ffurrer2/extract-release-notes@v2
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        draft: true
        prerelease: false
        body: |
          ${{ steps.extract-release-notes.outputs.release_notes }}
          ____
          You can download the latest source script and execute it from the commandline, or try these self-contained packages, which don't require the installation of Python or dependencies:
          - Linux:
            - Stand-alone: [JWLManager_${{ github.ref_name }}](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/JWLManager_${{ github.ref_name }})
          - Windows 10/11:
            - Stand-alone: [JWLManager_${{ github.ref_name }}.exe](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/JWLManager_${{ github.ref_name }}.exe)
            - Zipped folder: [JWLManager_${{ github.ref_name }}.zip](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/JWLManager_${{ github.ref_name }}.zip)
          - macOS 11/12/13:
            - Zipped app: [JWLManager_${{ github.ref_name }}.app.zip](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/JWLManager_${{ github.ref_name }}.app.zip)
        files: |
          JWLManager_${{ github.ref_name }}
          JWLManager_${{ github.ref_name }}.exe
          JWLManager_${{ github.ref_name }}.zip
          JWLManager_${{ github.ref_name }}.app.zip
